"""add subscription level

Revision ID: 313a69cfd219
Revises: 1500cc916f4d
Create Date: 2025-04-30 21:59:05.162555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313a69cfd219'
down_revision = '1500cc916f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_level', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_level')

    # ### end Alembic commands ###
