"""Add budget_limit column to Category

Revision ID: 459c44b23b4e
Revises: 
Create Date: 2025-04-29 19:41:45.430052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459c44b23b4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget_limit', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('budget_limit')

    # ### end Alembic commands ###
