"""Add show_budget_warning to user

Revision ID: 98c66f3b5b50
Revises: 459c44b23b4e
Create Date: 2025-04-30 00:15:18.560073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98c66f3b5b50'
down_revision = '459c44b23b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('show_budget_warning', sa.Boolean(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_column('profile_image')
        batch_op.drop_column('date_joined')
        batch_op.drop_column('subscription_level')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_level', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('date_joined', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('show_budget_warning')
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
